INSERT INTO COMMON (COMMON_CODE) VALUES ('LANG');
INSERT INTO COMMON (COMMON_CODE) VALUES ('USER_TYPE');

INSERT INTO COMMON_CODE (COMMON_CODE, COMMON_NAME, COMMON_VALUE, COMMON_ID)
VALUES 
('LANG', 'English', '1', 1),
('LANG', 'Korean', '2', 1),
('USER_TYPE', 'Regular User', '1', 2),
('USER_TYPE', 'Administrator', '2', 2);

INSERT INTO MEMBERS (USER_ID, PASSWD, USER_NAME, EMAIL, TEL, AGE, SIGNIN_DATE, LANG, VIEW_ADULT, SAVE_HISTORY, USER_TYPE)
VALUES 
('user', '1234', 'Alice', 'alice@example.com', '01012345678', 25, CURRENT_DATE, 'en', 'N', 'Y', 'USER'),
('admin', '1234', 'Bob', 'bob@example.com', '01087654321', 35, CURRENT_DATE, 'ko', 'Y', 'Y', 'ADMIN');

INSERT INTO GENRE (GENRE_CODE, GENRE_NAME)
VALUES 
('ACT', 'Action'),
('COM', 'Comedy'),
('ROM', 'Romance');

INSERT INTO CREATOR (CREATOR_CODE, CREATOR_NAME, GENDER, BIRTH, HOMETOWN)
VALUES 
('D001', 'Christopher Nolan', 'M', '1970-07-30', 'London'),
('A001', 'Leonardo DiCaprio', 'M', '1974-11-11', 'Los Angeles'),
('A002', 'Anne Hathaway', 'F', '1982-11-12', 'New York');

INSERT INTO MOVIE (
    MOVIE_CODE, GENRE_CODEA, MOVIE_NAME, DIRECT_CODEA, ACTOR_CODEA, RUNTIME, RATING, MOVIE_RELEASE, SALES
)
VALUES (
    'M001', 'ACT', 'Inception', 'D001', 'A001', '02:28:00', 15, '2010-07-16', 830000000
);

INSERT INTO THEATER (THEATER_CODE, THEATER_NAME, THEATER_ACTIVE, TOTALSEAT)
VALUES ('T001', 'CGV Gangnam', 'Y', 100);

INSERT INTO SEAT (SEAT_CODE, THEATER_CODE, PRICE, DISCOUNT_PER, SEAT_ACTIVE, RESERVED)
VALUES 
('A1', 'T001', 12000, 0, 'Y', 'N'),
('A2', 'T001', 12000, 10, 'Y', 'N');

INSERT INTO RESERVATION (RESERVE_CODE, RESERVE_DATE, USER_ID, THEATER_CODE, MOVIE_CODE, SEAT_CODE, PRICE)
VALUES ('R001', CURRENT_DATE, 'user01', 'T001', 'M001', 'A1', 12000);

INSERT INTO WATCH_HISTORY (USER_ID, MOVIE_CODE, WATCH_DATE, WATCH_TIME)
VALUES ('user01', 'M001', CURRENT_DATE, '20:00:00');

INSERT INTO ORDER_HISTORY (ORDER_CODE, USER_ID, MOVIE_CODE, PRICE, ORDER_DATE)
VALUES ('O001', 'user01', 'M001', 10000, CURRENT_DATE);

INSERT INTO CREDIT_CARD (CARD_NUM, USER_ID, EXP_MONTH, CVC, BANK_CODE)
VALUES ('1234567890123456', 'user01', '202512', '123', 'KB001');

INSERT INTO NOTICE (NOTICE_CODE, CATEGORY, WRITE_DATE, TITLE, CONTENT, WRITER)
VALUES ('N001', 'INFO', CURRENT_DATE, 'Welcome', 'Welcome to our movie service!', 'admin01');

INSERT INTO FAQ (FAQ_CODE, QUESTION, ANSWER)
VALUES ('F001', 'How to reserve?', 'Go to the movie page and click "Reserve".');

INSERT INTO QNA (QNA_CODE, TITLE, CONTENT, USER_ID, WRITE_DATE)
VALUES ('Q001', 'Can I cancel a reservation?', 'I want to cancel my ticket.', 'user01', CURRENT_DATE);


SELECT * FROM members;