spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true
      additional-paths:
        - src/main/java

  config:
    import: optional:file:./db.env

  application:
    name: project

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: socialquizwebsite@gmail.com
    password: tabpuahsodkebxqk
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

server:
  port: ${SERVER_PORT}

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
